version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region ap-northeast-1 --no-include-email)
      - PROJECT_NAME=echo
      - SERVICE_NAME=echo_server
      - REPOSITORY_URI=373656256964.dkr.ecr.ap-northeast-1.amazonaws.com/echo/server
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Doker Image
      - docker build -t echo/server ./server
      - docker tag echo/server $REPOSITORY_URI:$IMAGE_TAG
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Pushing docker image
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - cd server && ./update-service.sh
