version: 0.2
phases:
  pre_build:
    commands:
      - if [ -z "$TAG" ]; then echo 'Missing TAG'; exit 1; fi
      - if [ -z "$REPOSITORY_URI" ]; then echo 'Missing REPOSITORY_URI'; exit 1; fi
      - echo TAG is $TAG
      - echo REPOSITORY_URI is $REPOSITORY_URI
      - aws --version
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region ap-northeast-1 --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Doker Image
      - docker build -t echo/server ./server
      - docker tag echo/server $REPOSITORY_URI:$TAG
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Pushing docker image
      - docker push $REPOSITORY_URI:$TAG
